#!/bin/bash

set -x

# npm run test-travis &&

git checkout deploy &&
git merge master &&
npm run clean &&
npm run build &&
git add . &&
git commit -m 'auto-build on `date +%Y%m%d`' ;
git push origin deploy &&
git checkout master &&

echo "piousbox-render build ok"
