#!/bin/bash

set -x

# npm run test-travis &&
git branch

./scripts/version_bump
git checkout deploy
git merge master
npm run clean
npm install
npm run build &&
cp dist/js/app*.js index.js &&
git add .
git commit -m 'auto-build on `date +%Y%m%d`' ;
git push origin deploy &&
npm publish &&
git checkout master &&
git merge deploy &&

echo "piousbox-render build ok"
